backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

publish_mode: editorial_workflow

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit

  - label: "Pages"
    name: "pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - label: "Testimonial"
            name: "testimonial"
            widget: "list"
            fields:
              - {label: Quote, name: quote, widget: text}
              - {label: Client, name: client, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Company, name: company, widget: string}
      - file: "site/content/services/_index.md"
        label: "Services"
        name: "services"
        fields:
          - {label: "Title", name: "title", widget: "string"}
      - file: "site/content/work/_index.md"
        label: "Work"
        name: "work"
        fields:
          - {label: "Title", name: "title", widget: "string"}
      - file: "site/content/about/_index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
      - file: "site/content/blog/_index.md"
        label: "Blog"
        name: "blog"
        fields:
          - {label: "Title", name: "title", widget: "string"}
      - file: "site/content/contact/_index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}

  - label: "Blog"
    name: "blog"
    folder: "site/content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Case Study"
    name: "case_study"
    folder: "site/content/work"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Featured Image, name: thumbnail, widget: image }
      - { label: Brief, name: brief, widget: object, fields: [
          { label: Body, name: body, widget: markdown }]}
      - { label: Solution, name: solution, widget: object, fields: [
          { label: Body, name: body, widget: markdown }]}
      - { label: Results, name: results, widget: object, fields: [
          { label: Body, name: body, widget: markdown }]}
      - { label: SEO, name: seo, widget: object, fields: [
          { label: Meta Title, name: meta_title, widget: string },
          { label: Meta Description, name: meta_decription, widget: text },
          { label: Keywords, name: keywords, widget: string }]}

  - label: Services
    name: services
    folder: "site/content/services"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Intro, name: intro, widget: text }
      - { label: Icon, name: icon, widget: image }
      - { label: Image, name: image, widget: image, required: false }
      - { label: Content, name: body, widget: markdown }

  - name: "settings"
    label: "Settings"
    files:
      - label: "General"
        name: "general"
        file: "site/data/settings.json"
        description: "General app settings"
        fields:
          - { label: "App Title", name: "app_title", widget: "string" }
      - label: Language
        name: language
        file: "site/data/language.json"
        description: "Language for site forms"
        fields:
          - { label: "Full Name Label", name: "fullname_label", widget: "string" }
          - { label: "Full Name Placeholder", name: "fullname_placeholder", widget: "string" }
      - label: Logo
        name: logo
        file: "site/data/logo.json"
        description: "Upload a logo for your brand. SVG | PNG | JPG"
        fields:
          - { label: "Your Logo", name: "logo", widget: "image" }
      - label: Site Navigation
        name: site_navigation
        file: "site/data/menu.json"
        description: "Set custom titles for the nav items"
        fields:
          - { label: "Services Title", name: "services", widget: "string" }
          - { label: "Work Title", name: "work", widget: "string" }
          - { label: "About Title", name: "about", widget: "string" }
          - { label: "Blog Title", name: "blog", widget: "string" }
          - { label: "Contact Title", name: "contact", widget: "string" }
