backend:
  name: git-gateway

publish_mode: editorial_workflow
media_folder: site/static/img
public_folder: img

collections:

  - label: Pages
    name: pages
    files:
      - file: site/content/_index.md
        label: Home Page
        name: home
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Image, name: image, widget: image }
          - label: Banner services
            name: banner
            widget: list
            fields:
              - { label: Service, name: service, widget: relation, collection: services, searchFields: [title], valueField: title }
          - label: Testimonial
            name: testimonial
            widget: list
            fields:
              - {label: Quote, name: quote, widget: text}
              - {label: Client, name: client, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Company, name: company, widget: string}
          - label: Logo Wall
            name: logo_wall
            widget: list
            fields:
              - { label: Client, name: client, widget: relation, collection: clients, searchFields: [title, contact], valueField: title }
          - { label: Featured Case Study, name: featured_work, widget: relation, collection: case_study, searchFields: [title], valueField: title }
          - { label: Featured Video, name: featured_video, widget: string }
          - label: Service Picker
            name: service_picker
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Slide
                name: picker_slide
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Subtitle, name: subtitle, widget: string, required: false }
                  - { label: Intro, name: info, widget: text, required: false }
                  - { label: Image, name: image, widget: image }
                  - label: Services
                    name: service_list
                    widget: list
                    fields:
                      - { label: Service, name: service, widget: relation, collection: services, searchFields: [title], valueField: title }


      - file: site/content/services/_index.md
        label: Services
        name: services
        fields:
          - { label: Title, name: title, widget: string }
          - label: Banner services
            name: banner
            widget: list
            fields:
              - { label: Service, name: service, widget: relation, collection: services, searchFields: [title], valueField: title }

      - file: site/content/work/_index.md
        label: Work
        name: work
        fields:
          - { label: Title, name: title, widget: string }

      - file: site/content/about/_index.md
        label: About
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - label: Our Mission
            name: mission
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Body, name: body, widget: markdown }
          - label: Our Story
            name: story
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Highlighted Text, name: highlight, widget: text }
              - { label: Body, name: body, widget: markdown }
          - label: Our Team
            name: team
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Members
                name: members
                widget: list
                fields:
                  - { label: Member Name, name: name, widget: string }
                  - { label: Position, name: position, widget: string }
          - label: Logo Wall
            name: logo_wall
            widget: list
            fields:
              - { label: Client, name: client, widget: relation, collection: clients, searchFields: [title, contact], valueField: title }

      - file: site/content/blog/_index.md
        label: Blog
        name: blog
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }

      - file: site/content/contact/_index.md
        label: Contact
        name: contact
        fields:
          - { label: Title, name: title, widget: string }


  - label: Landing Pages
    name: landing_pages
    folder: site/content/landing
    create: true
    url: {{ title }}
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: publishDate, widget: datetime }
      - { label: Intro, name: intro, widget: text }
      - label: Choice
        name: choice
        widget: list
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Summary, name: summary, widget: text }
          - { label: Image, name: image, widget: image }
          - { label: CTA Text, name: cta, widget: string }
          - { label: Download, name: download, widget: file }


  - label: Blog
    name: blog
    folder: site/content/blog
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: publishDate, widget: datetime }
      - { label: Author, name: author, widget: relation, collection: authors, searchFields: [first_name, surname], valueField: first_name }
      - { label: Body, name: body, widget: markdown }


  - label: Authors
    name: authors
    folder: site/content/authors
    create: true
    slug: "{{first_name}}-{{surname}}"
    editor:
      preview: false
    fields:
      - { label: First Name, name: first_name, widget: string }
      - { label: Surname, name: surname, widget: string }
      - { label: Avatar, name: avatar, widget: image, required: false }


  - label: "Case Study"
    name: "case_study"
    folder: "site/content/work"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Meta Description, name: description, widget: string }
      - { label: Meta Keywords, name: keywords, widget: string }
      - { label: Featured Image, name: thumbnail, widget: image }
      - { label: Client, name: client, widget: relation, collection: clients, searchFields: [title, contact], valueField: title }
      - { label: Brief, name: brief, widget: object, fields: [
          { label: Body, name: body, widget: markdown }]}
      - label: Services
        name: service_list
        widget: list
        fields:
          - { label: Service, name: service, widget: relation, collection: services, searchFields: [title], valueField: title }
      - { label: Solution, name: solution, widget: object, fields: [
          { label: Body, name: body, widget: markdown }]}
      - label: Results
        name: results
        widget: object
        fields:
          - label: Key Results
            name: key_results
            widget: list
            fields:
              - { label: Big Text, name: big_text, widget: string }
              - { label: Supportive Text, name: supportive_text, widget: string, required: false}
          - label: Body
            name: body
            widget: markdown


  - label: Services
    name: services
    folder: site/content/services
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Intro, name: intro, widget: text, required: false }
      - { label: Icon, name: icon, widget: image, required: false }
      - { label: Icon Reverse Color Scheme, name: icon_reverse, widget: image, required: false }
      - { label: Image, name: image, widget: image, required: false }
      - label: Service Type
        name: serviceType
        widget: select
        options:
          - { label: Primary, value: Primary }
          - { label: Secondary, value: Secondary }
      - { label: Content, name: body, widget: markdown, required: false }


  - label: Clients
    name: clients
    folder: "site/content/clients"
    create: true
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Logo, name: logo, widget: image, required: false }
      - { label: Location, name: location, widget: string }
      - { label: Contact, name: contact, widget: string, required: false }
      - { label: Contact Position, name: contact_position, string, required: false }


  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - label: Brand
        name: brand
        file: site/data/brand.yml
        fields:
          - { label: Company Name, name: company_name, widget: string }
          - { label: Company Tagline, name: company_tagline, widget: text }
          - label: Social
            name: social
            widget: list
            fields:
              - { label: Name, name: Name, widget: string }
              - { label: URL, name: URL, widget: string }

      - label: Contact Information
        name: contact_info
        file: site/data/contact.yml
        fields:
          - { label: Email Address, name: email, widget: string }
          - { label: Telephone Number, name: number, widget: string }
          - label: Address
            name: address
            widget: object
            fields:
              - { label: Address Line 1, name: line_1, widget: string }
              - { label: Address Line 2, name: line_2, widget: string, required: false }
              - { label: Suburb, name: suburb, widget: string }
              - { label: State, name: state, widget: string }
              - { label: Postcode, name: postcode, widget: number }
              - { label: Country, name: country, widget: string, required: false }
          - label: Open Hours
            name: open_hours
            widget: list
            fields:
              - { label: "Day(s)", name: days, widget: string }
              - { label: Hours, name: hours, widget: string }

      - label: Language
        name: language
        file: "site/data/language.json"
        description: "Language for site forms"
        fields:
          - { label: "Full Name Label", name: "fullname_label", widget: "string" }
          - { label: "Full Name Placeholder", name: "fullname_placeholder", widget: "string" }

      - label: Logo
        name: logo
        file: "site/data/logo.json"
        description: "Upload a logo for your brand. SVG | PNG | JPG"
        fields:
          - { label: "Your Logo", name: "logo", widget: "image" }

      - label: Site Navigation
        name: site_navigation
        file: "site/data/menu.json"
        description: "Set custom titles for the nav items"
        fields:
          - { label: "Services Title", name: "services", widget: "string" }
          - { label: "Work Title", name: "work", widget: "string" }
          - { label: "About Title", name: "about", widget: "string" }
          - { label: "Blog Title", name: "blog", widget: "string" }
          - { label: "Contact Title", name: "contact", widget: "string" }
