backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

# publish_mode: editorial_workflow

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit

  - name: "settings"
    label: "Settings"
    files:
      - name: "general"
        label: "General"
        file: "site/data/settings.json"
        description: "General app settings"
        fields:
          - { label: "App Title", name: "app_title", widget: "string" }
