baseurl: "/"
languageCode: "en-us"
languageLang: "en"
title: "Marketplace Strategy Solutions"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds: ["RSS", "taxonomy", "taxonomyTerm"]

mapsKey: AIzaSyCmu1ykB9J4_b_bqWbm_n9vsQHWmIdZ4iE

menu:
  main:
    - Name: "Home"
      URL: "/"
      weight: 1
      Identifier: "home"
    - Name: "Services"
      URL: "/services/"
      weight: 2
      Identifier: "services"
    - Name: "Work"
      URL: "/work/"
      weight: 3
      Identifier: "work"
    - Name: "About"
      URL: "/about/"
      weight: 4
      Identifier: "about"
    - Name: "Blog"
      URL: "/blog/"
      weight: 5
      Identifier: "blog"
    - Name: "Contact"
      URL: "/contact/"
      weight: 6
      Identifier: "contact"
  services:
    - Name: "Home"
      URL: "/"
      weight: 2
      Identifier: "home"
    - Name: "Services"
      URL: "/services/"
      weight: 1
      Identifier: "services"
    - Name: "Contact"
      URL: "/contact/"
      weight: 3
      Identifier: "contact"
  work:
    - Name: "Home"
      URL: "/"
      weight: 2
      Identifier: "home"
    - Name: "Work"
      URL: "/work/"
      weight: 1
      Identifier: "work"
    - Name: "Contact"
      URL: "/contact/"
      weight: 3
      Identifier: "contact"
